In [3]:
import numpy as np
l=[[10,20,30,40],[20,40,50,60]]
a=np.array(l)
print(a)
type(a)









[[10 20 30 40]
 [20 40 50 60]]


numpy.ndarray

# Attributes 

In [16]:
print("ndim: ",a.ndim)
print("shape: ",a.shape)
print("Size: ",a.size)
print("dtype: ",a.dtype)
print("iteamsize: ",a.itemsize)


ndim:  2
shape:  (2, 4)
Size:  8
dtype:  int64
iteamsize:  8


# indexing

In [22]:
print(a[0][0])
a[0,1]



10


np.int64(20)

# Slicing

In [26]:
a1=np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])
print(a1)

[[15 16 17]
 [25 26 27]
 [35 36 37]
 [45 46 47]]


In [28]:
a1[1,]#fiest index denotes row 

array([25, 26, 27])

In [30]:
a1[:,1]

array([16, 26, 36, 46])

In [31]:
a1[1:3,1:3]

array([[26, 27],
       [36, 37]])

In [32]:
a1[1:3,]

array([[25, 26, 27],
       [35, 36, 37]])

In [33]:
a1[:,1:3]

array([[16, 17],
       [26, 27],
       [36, 37],
       [46, 47]])

In [34]:
a1[1:3,1]

array([26, 36])

In [35]:
a1[1:3,:1]

array([[25],
       [35]])

In [36]:
a1[1:3,1:]

array([[26, 27],
       [36, 37]])

# Arithmetic Opr

In [39]:
a1=np.array([1,2,3,4])
a2=np.array([10,20,30,40])
a1,a2

(array([1, 2, 3, 4]), array([10, 20, 30, 40]))

In [40]:
# +
a1+a2

array([11, 22, 33, 44])

In [41]:
a1-a2

array([ -9, -18, -27, -36])

In [42]:
a1*a2

array([ 10,  40,  90, 160])

In [45]:
a2/a1

array([10., 10., 10., 10.])

In [46]:
a2//a1

array([10, 10, 10, 10])

In [48]:
a1%a2

array([1, 2, 3, 4])

## Creating Arrays With a Defined Data Type

In [26]:
adtype=np.array([1,1,3],dtype='f')
#you can define names like (float,int,str) or ('S','f','i','u','b','F'=complexnumber)
                
print(adtype)# if not able to convert then it will raise an Value error

[1. 1. 3.]


In [28]:
adtype=np.array([1,1,0,3],dtype=bool)
adtype

array([ True,  True, False,  True])

# astype :
## The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [29]:
ast=adtype.astype(int)
ast

array([1, 1, 0, 1])

# Reshape()
### By reshaping we can add or remove dimensions or change number of elements in each dimension.
### is doesn,t changes original shape 
### must give M X N pattern 
### you can give any one dimention if you don't know the dimentions then it will calculate automaticly 


In [31]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [37]:
arr1.reshape(4,3)
print(arr1)
arr1.reshape(4,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
arr1.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [39]:
arr1.reshape([2,-1])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# Flattening the arrays
### Flattening array means converting a multidimensional array into a 1D array.

In [40]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2.flatten()

array([1, 2, 3, 4, 5, 6])

# np.Sort() 
## it sort array but never change original array

# argsort()- 
## it gives the index of shifted elements after sorting

In [41]:
arr3=np.array([10,20,30,40,90,3,2,100,6])
arr3

array([ 10,  20,  30,  40,  90,   3,   2, 100,   6])

In [68]:
print(np.sort(arr3)[::-1])
print(arr3)


[100  90  40  30  20  10   6   3   2]
[  2   3   6  10  20  30  40  90 100]


In [65]:
arr4=np.array([1,2,6,4,5,8,1])
print(arr3.sort())
print(arr3)

None
[  2   3   6  10  20  30  40  90 100]


In [69]:
print(np.argsort(arr4))

[0 6 1 3 4 2 5]


In [78]:
arr2d=[[10,30,20],[40,5,60]]
arr2d

[[10, 30, 20], [40, 5, 60]]

In [79]:
np.sort(arr2d)

array([[10, 20, 30],
       [ 5, 40, 60]])

In [81]:
np.sort(arr2d,axis=0)#0 for colum sort #1 for row sort default is row

array([[10,  5, 20],
       [40, 30, 60]])

In [84]:
np.argsort(arr2d)

array([[0, 2, 1],
       [1, 0, 2]])

# Statics Functions

In [85]:
arr5=np.array([10,20,30,40,50,60,70,80,100])

In [89]:
print(np.min(arr5),np.max(arr5),np.sum(arr5),np.prod(arr5))

10 100 460 403200000000000


In [93]:
print(np.mean(arr5), np.median(arr5),np.var(arr5),np.std(arr5))

51.111111111111114 50.0 765.4320987654321 27.666443551086072
